/**
 * Procedural PBR texture synthesis for the eight terrain biomes.
 *
 * **These textures are generated, not authored.** There is not a single image
 * file in the repo and the spec's 25 MB asset budget is therefore spent at
 * zero. That is a deliberate trade with real costs and real benefits, and both
 * belong on the record:
 *
 *   + no download, no decode, no KTX2 toolchain, no licence provenance;
 *   + every biome is generated by the same code, so adding a ninth costs a
 *     function rather than a texture set;
 *   + the synthesis is seeded, so the world is reproducible from an integer.
 *   − procedural granite is not photographed granite. Noise gives structure and
 *     scale but not the *specificity* of a real surface — the lichen that grows
 *     on one face and not the next, the particular way a quartz vein cuts. The
 *     result reads as convincing ground, not as a photograph of ground.
 *
 * Every function here is periodic over the unit square, because the output goes
 * into a texture that is tiled across kilometres. A non-tiling noise would put a
 * hard seam on every repeat and no amount of stochastic blending would hide it.
 * Periodicity is achieved by wrapping the *lattice index* rather than the
 * coordinate: `aeMtHash` takes the integer cell modulo the octave's period, so
 * the gradients at u=0 and u=1 are the same gradients by construction.
 *
 * Channel packing (spec 2.2):
 *   albedoAO   rgb albedo (linear) · a ambient occlusion
 *   normalRH   rg normal.xy (0.5-centred) · b roughness · a height
 */

import { wgslFn } from 'three/tsl';

// ---------------------------------------------------------------------------
// Periodic hashing and noise
// ---------------------------------------------------------------------------

export const fnMtHash = wgslFn(/* wgsl */ `
fn aeMtHash( ix: i32, iy: i32, period: i32, seed: i32 ) -> u32 {
  // Wrap into [0, period). WGSL's % follows the sign of the dividend, so the
  // +period round-trip is needed for the negative cells a domain warp produces.
  let wx = ( ( ix % period ) + period ) % period;
  let wy = ( ( iy % period ) + period ) % period;
  // WGSL requires the parentheses: it refuses to guess a precedence between
  // '*' and '^'.
  var h = ( bitcast<u32>( wx ) * 0x27d4eb2du ) ^ ( bitcast<u32>( wy ) * 0x165667b1u ) ^ bitcast<u32>( seed );
  h = h ^ ( h >> 15u );
  h = h * 0x2c1b3c6du;
  h = h ^ ( h >> 12u );
  h = h * 0x297a2d39u;
  h = h ^ ( h >> 15u );
  return h;
}
`);

export const fnMtRand2 = wgslFn(
  /* wgsl */ `
fn aeMtRand2( ix: i32, iy: i32, period: i32, seed: i32 ) -> vec2f {
  let h = aeMtHash( ix, iy, period, seed );
  return vec2f(
    f32( h & 0xffffu ) / 65536.0,
    f32( ( h >> 16u ) & 0xffffu ) / 65536.0
  );
}
`,
  [fnMtHash],
);

/** Periodic gradient (Perlin) noise, ≈[-1,1]. */
export const fnMtPerlin = wgslFn(
  /* wgsl */ `
fn aeMtPerlin( p: vec2f, period: f32, seed: i32 ) -> f32 {
  let ip = floor( p );
  let f = p - ip;
  let ix = i32( ip.x );
  let iy = i32( ip.y );
  let per = max( i32( period ), 1 );

  let a00 = aeMtRand2( ix,     iy,     per, seed ).x * 6.28318530718;
  let a10 = aeMtRand2( ix + 1, iy,     per, seed ).x * 6.28318530718;
  let a01 = aeMtRand2( ix,     iy + 1, per, seed ).x * 6.28318530718;
  let a11 = aeMtRand2( ix + 1, iy + 1, per, seed ).x * 6.28318530718;

  let n00 = dot( vec2f( cos( a00 ), sin( a00 ) ), f );
  let n10 = dot( vec2f( cos( a10 ), sin( a10 ) ), f - vec2f( 1.0, 0.0 ) );
  let n01 = dot( vec2f( cos( a01 ), sin( a01 ) ), f - vec2f( 0.0, 1.0 ) );
  let n11 = dot( vec2f( cos( a11 ), sin( a11 ) ), f - vec2f( 1.0, 1.0 ) );

  let u = f * f * f * ( f * ( f * 6.0 - 15.0 ) + 10.0 );
  return mix( mix( n00, n10, u.x ), mix( n01, n11, u.x ), u.y ) * 1.4142135623730951;
}
`,
  [fnMtRand2],
);

/** Periodic fBm. Each octave doubles both the frequency and the wrap period. */
export const fnMtFbm = wgslFn(
  /* wgsl */ `
fn aeMtFbm( p: vec2f, period: f32, seed: i32, octaves: i32 ) -> f32 {
  var sum = 0.0;
  var amp = 1.0;
  var freq = 1.0;
  for ( var i = 0; i < octaves; i = i + 1 ) {
    sum = sum + aeMtPerlin( p * freq, period * freq, seed + i * 977 ) * amp;
    amp = amp * 0.5;
    freq = freq * 2.0;
  }
  return sum * 0.5;
}
`,
  [fnMtPerlin],
);

/**
 * Periodic Worley/Voronoi.
 *
 * Returns (F1, F2 − F1, cell id in 0..1). F2 − F1 is the useful one for cracks
 * and pebble borders: it goes to zero exactly on the cell boundary regardless of
 * how far apart the seeds are, so the crack width does not vary with cell size
 * the way a plain F1 threshold does.
 */
export const fnMtVoronoi = wgslFn(
  /* wgsl */ `
fn aeMtVoronoi( p: vec2f, period: f32, seed: i32 ) -> vec3f {
  let ip = floor( p );
  let f = p - ip;
  let per = max( i32( period ), 1 );

  var f1 = 8.0;
  var f2 = 8.0;
  var id = 0.0;

  for ( var j = -1; j <= 1; j = j + 1 ) {
    for ( var i = -1; i <= 1; i = i + 1 ) {
      let cell = vec2f( f32( i ), f32( j ) );
      let jitter = aeMtRand2( i32( ip.x ) + i, i32( ip.y ) + j, per, seed );
      let d = length( cell + jitter - f );
      if ( d < f1 ) {
        f2 = f1;
        f1 = d;
        id = aeMtRand2( i32( ip.x ) + i, i32( ip.y ) + j, per, seed + 7717 ).x;
      } else if ( d < f2 ) {
        f2 = d;
      }
    }
  }
  return vec3f( f1, f2 - f1, id );
}
`,
  [fnMtRand2],
);

// ---------------------------------------------------------------------------
// The eight materials
// ---------------------------------------------------------------------------

/**
 * Albedo (linear rgb) and height for one material at a tiling uv.
 *
 * Height is the channel that does the most work downstream: it drives the
 * height-based blend between splat layers (grass settling *between* stones
 * rather than over them), the parallax occlusion mapping on rock, and — via a
 * second pass — both the normal map and the cavity AO. So each material's
 * height is authored as a real surface displacement in roughly 0..1, not as a
 * decorative greyscale.
 *
 * `layer` matches the biome order in `splat.ts`:
 *   0 rock · 1 scree · 2 meadow · 3 dry grass · 4 forest floor ·
 *   5 sand · 6 mud · 7 snow
 */
export const fnMatAlbedoHeight = wgslFn(
  /* wgsl */ `
fn aeMatAlbedoHeight( uv: vec2f, layer: f32, seed: i32 ) -> vec4f {
  let li = i32( layer + 0.5 );
  let s = seed + li * 8191;

  if ( li == 0 ) {
    // --- ГРАНИТ ---------------------------------------------------------
    // Three structures, and the order matters. Bedding planes give the rock a
    // direction (without one it reads as concrete); the joint network breaks
    // that direction into blocks; the speckle is the mineral grain that makes
    // it granite rather than sandstone.
    let bedAngle = 0.32;
    let dir = vec2f( cos( bedAngle ), sin( bedAngle ) );
    let along = dot( uv, dir ) * 8.0;
    let warp = aeMtFbm( uv * 6.0, 6.0, s + 11, 3 ) * 0.55;
    let strata = abs( fract( along + warp ) - 0.5 ) * 2.0;
    let bedding = pow( strata, 1.6 );

    // Two joint sets at different spacings, and the coarse one decides where the
    // fine one is allowed to show. One Worley scale on its own gives cells of a
    // single size, and Worley cells are hexagonal on average — the close-up shot
    // read as a regular honeycomb across the whole face, which is worse than no
    // joints at all. Real granite jointing is a coarse master set with finer
    // cross-joints inside some of the blocks and not others.
    let joints = aeMtVoronoi( uv * 3.0, 3.0, s + 23 );
    let fineJoints = aeMtVoronoi( uv * 9.0, 9.0, s + 29 );
    let crackMaster = 1.0 - smoothstep( 0.0, 0.055, joints.y );
    let crackFine = ( 1.0 - smoothstep( 0.0, 0.09, fineJoints.y ) )
      * smoothstep( 0.35, 0.75, joints.z );
    let crack = max( crackMaster, crackFine * 0.65 );
    let blockTone = mix( joints.z, fineJoints.z, 0.35 );

    let grain = aeMtFbm( uv * 130.0, 130.0, s + 41, 3 );
    let mid = aeMtFbm( uv * 24.0, 24.0, s + 53, 4 );

    var h = 0.62 + bedding * 0.22 + mid * 0.14 - crack * 0.34 + grain * 0.03;
    h = clamp( h, 0.0, 1.0 );

    // Granite is not grey, it is a warm grey with a blue shadow — a pure
    // neutral reads as plastic under any sky.
    let base = mix( vec3f( 0.148, 0.144, 0.139 ), vec3f( 0.281, 0.272, 0.259 ), blockTone );
    var c = base * ( 0.80 + mid * 0.30 + bedding * 0.16 );
    // Feldspar/quartz speckle: sparse, bright, high contrast.
    let speck = smoothstep( 0.42, 0.72, aeMtFbm( uv * 260.0, 260.0, s + 67, 2 ) + 0.5 );
    c = mix( c, vec3f( 0.46, 0.45, 0.43 ), speck * 0.35 );
    c = c * ( 1.0 - crack * 0.55 );
    return vec4f( c, h );
  }

  if ( li == 1 ) {
    // --- ОСЫПЬ ----------------------------------------------------------
    // Two Worley scales with different jitter so the clast size actually
    // varies; one scale alone gives a suspiciously regular gravel.
    let big = aeMtVoronoi( uv * 11.0, 11.0, s + 3 );
    let small = aeMtVoronoi( uv * 27.0, 27.0, s + 5 );
    let bigDome = clamp( 1.0 - big.x * 1.35, 0.0, 1.0 );
    let smallDome = clamp( 1.0 - small.x * 1.7, 0.0, 1.0 );
    // Which scale wins is itself random, so big and small stones interleave
    // rather than the small ones sitting on top of the big ones everywhere.
    let pick = step( 0.45, big.z );
    let dome = mix( smallDome * 0.7, bigDome, pick );
    let dust = aeMtFbm( uv * 70.0, 70.0, s + 13, 3 );

    let h = clamp( 0.30 + dome * 0.62 + dust * 0.06, 0.0, 1.0 );

    let stoneTone = mix( big.z, small.z, 1.0 - pick );
    var c = mix( vec3f( 0.124, 0.117, 0.108 ), vec3f( 0.256, 0.244, 0.225 ), stoneTone );
    // Freshly broken faces are lighter than weathered ones.
    c = mix( c, c * 1.45, smoothstep( 0.55, 0.95, dome ) * 0.5 );
    c = c * ( 0.86 + dust * 0.28 );
    return vec4f( c, h );
  }

  if ( li == 2 || li == 3 ) {
    // --- ТРАВА (луговая и сухая) ----------------------------------------
    // Grass at metre scale is not blades, it is clumps: a tuft structure with
    // shadow between the tufts. Blades are phase 7's job as geometry; painting
    // them here would fight the geometry and alias horribly at distance.
    let dry = f32( li == 3 );

    let clump = aeMtVoronoi( uv * 17.0, 17.0, s + 3 );
    let tuft = clamp( 1.0 - clump.x * 1.55, 0.0, 1.0 );
    // Strands: a stretched noise gives the tufts a lay direction.
    let lay = aeMtFbm( vec2f( uv.x * 90.0, uv.y * 22.0 ), 90.0, s + 19, 3 );
    let patchTone = aeMtFbm( uv * 5.0, 5.0, s + 31, 3 );
    let fine = aeMtFbm( uv * 150.0, 150.0, s + 43, 2 );

    let h = clamp( 0.42 + tuft * 0.40 + lay * 0.12 + fine * 0.05, 0.0, 1.0 );

    // Two greens and a straw, mixed by patch noise and by how exposed the tuft
    // is. Grass with one green in it looks like a golf course.
    let lush = mix( vec3f( 0.052, 0.098, 0.030 ), vec3f( 0.132, 0.196, 0.062 ), tuft );
    let straw = mix( vec3f( 0.137, 0.113, 0.053 ), vec3f( 0.312, 0.259, 0.120 ), tuft );
    var c = mix( lush, straw, clamp( dry * 0.82 + patchTone * 0.45 + 0.10, 0.0, 1.0 ) );
    // Dead matter at the base of the clumps, more of it in the dry variant.
    c = mix( c * 0.55, c, smoothstep( 0.05, 0.55, tuft ) );
    c = c * ( 0.88 + patchTone * 0.34 + clump.z * 0.16 );
    c = c * ( 1.0 + fine * 0.18 );
    return vec4f( c, h );
  }

  if ( li == 4 ) {
    // --- ЛЕСНАЯ ПОДСТИЛКА ------------------------------------------------
    // Leaves as flattened Worley cells (a leaf is wider than it is long from
    // above), moss in the hollows, roots as a low-frequency ridge network.
    let leafP = vec2f( uv.x * 26.0, uv.y * 19.0 );
    let leaf = aeMtVoronoi( leafP, 26.0, s + 3 );
    let leafDome = clamp( 1.0 - leaf.x * 1.5, 0.0, 1.0 );
    let humus = aeMtFbm( uv * 40.0, 40.0, s + 17, 4 );
    let roots = 1.0 - smoothstep( 0.0, 0.09, aeMtVoronoi( uv * 4.0, 4.0, s + 29 ).y );
    let moss = smoothstep( 0.15, 0.62, aeMtFbm( uv * 9.0, 9.0, s + 37, 3 ) + 0.5 );

    let h = clamp( 0.40 + leafDome * 0.30 + roots * 0.24 + humus * 0.10, 0.0, 1.0 );

    let leafCol = mix( vec3f( 0.112, 0.068, 0.031 ), vec3f( 0.198, 0.127, 0.053 ), leaf.z );
    let soil = vec3f( 0.050, 0.041, 0.031 );
    var c = mix( soil, leafCol, smoothstep( 0.1, 0.6, leafDome ) );
    c = mix( c, vec3f( 0.044, 0.091, 0.036 ), moss * 0.55 );
    c = mix( c, vec3f( 0.091, 0.068, 0.047 ), roots * 0.6 );
    c = c * ( 0.82 + humus * 0.40 );
    return vec4f( c, h );
  }

  if ( li == 5 ) {
    // --- ПЕСОК -----------------------------------------------------------
    // Ripples are the whole identity of sand at this scale: a directional wave
    // whose crest line meanders. A pure sine reads as corrugated iron, so the
    // phase is displaced by noise before the wave is taken.
    let dirA = 0.9;
    let d = vec2f( cos( dirA ), sin( dirA ) );
    let meander = aeMtFbm( uv * 3.0, 3.0, s + 7, 3 ) * 1.8;
    let ripple = sin( ( dot( uv, d ) * 34.0 + meander ) * 6.28318530718 ) * 0.5 + 0.5;
    // Ripples are asymmetric: a long windward slope and a short lee face.
    let shaped = pow( ripple, 1.7 );
    let drift = aeMtFbm( uv * 7.0, 7.0, s + 23, 3 );
    let grain = aeMtFbm( uv * 300.0, 300.0, s + 41, 2 );

    let h = clamp( 0.45 + shaped * 0.30 + drift * 0.18 + grain * 0.04, 0.0, 1.0 );

    var c = mix( vec3f( 0.310, 0.255, 0.172 ), vec3f( 0.484, 0.419, 0.304 ), shaped * 0.7 + drift * 0.4 + 0.15 );
    c = c * ( 1.0 + grain * 0.22 );
    return vec4f( c, h );
  }

  if ( li == 6 ) {
    // --- ГРЯЗЬ / СУГЛИНОК ------------------------------------------------
    // Wet clay: smooth, dark, with desiccation polygons where it has started to
    // dry and standing water in the hollows.
    let cracks = aeMtVoronoi( uv * 13.0, 13.0, s + 3 );
    let crack = 1.0 - smoothstep( 0.0, 0.055, cracks.y );
    let lumps = aeMtFbm( uv * 22.0, 22.0, s + 19, 4 );
    let fine = aeMtFbm( uv * 110.0, 110.0, s + 31, 2 );
    let dryness = smoothstep( 0.05, 0.55, aeMtFbm( uv * 6.0, 6.0, s + 47, 3 ) + 0.5 );

    let h = clamp( 0.55 + lumps * 0.20 - crack * dryness * 0.38 + fine * 0.05, 0.0, 1.0 );

    var c = mix( vec3f( 0.042, 0.034, 0.024 ), vec3f( 0.120, 0.095, 0.066 ), lumps * 0.6 + cracks.z * 0.4 + 0.3 );
    // Where it has dried the clay goes pale and dusty; where it has not it is
    // near-black. That contrast is what makes mud read as *wet*.
    c = mix( c, c * 2.5 + vec3f( 0.02, 0.017, 0.012 ), dryness * 0.55 );
    c = c * ( 0.9 + fine * 0.25 );
    return vec4f( c, h );
  }

  // --- СНЕГ --------------------------------------------------------------
  // Wind-packed snow: long sastrugi ridges, a granular crust, and almost no
  // colour variation — what varies is the *normal*, which is why the height
  // here matters far more than the albedo.
  let windA = 0.55;
  let wd = vec2f( cos( windA ), sin( windA ) );
  let sastrugi = aeMtFbm( vec2f( dot( uv, wd ) * 26.0, dot( uv, vec2f( -wd.y, wd.x ) ) * 5.0 ), 26.0, s + 5, 3 );
  let drifts = aeMtFbm( uv * 4.0, 4.0, s + 13, 3 );
  let crust = aeMtFbm( uv * 120.0, 120.0, s + 29, 3 );

  let hs = clamp( 0.55 + sastrugi * 0.26 + drifts * 0.18 + crust * 0.06, 0.0, 1.0 );

  // Snow albedo is high but not 1.0 — 0.75 linear is a bright field under
  // direct sun; pushing it to white clips before the tonemapper ever sees it.
  var cs = vec3f( 0.74, 0.755, 0.79 ) * ( 0.94 + crust * 0.10 + drifts * 0.06 );
  // A faint blue in the troughs: snow scatters deeply and the light that comes
  // back out of a hollow has been through more of it.
  cs = mix( cs, vec3f( 0.62, 0.68, 0.80 ), clamp( 0.5 - hs, 0.0, 1.0 ) * 0.5 );
  return vec4f( cs, hs );
}
`,
  [fnMtFbm, fnMtVoronoi],
);

/**
 * Roughness for one material at a tiling uv.
 *
 * Separate from the albedo/height pass rather than packed into it because
 * `wgslFn` binds one function per node and a struct return would have to be
 * declared outside it. The duplicated noise is paid once per texel at startup,
 * not per frame, so the cost is a few milliseconds of boot.
 */
export const fnMatRoughness = wgslFn(
  /* wgsl */ `
fn aeMatRoughness( uv: vec2f, layer: f32, seed: i32 ) -> f32 {
  let li = i32( layer + 0.5 );
  let s = seed + li * 8191;

  if ( li == 0 ) {
    // Granite: matte overall, but the joints hold moisture and the freshly
    // exposed faces are slightly polished.
    let joints = aeMtVoronoi( uv * 3.0, 3.0, s + 23 );
    let crack = 1.0 - smoothstep( 0.0, 0.055, joints.y );
    let mid = aeMtFbm( uv * 24.0, 24.0, s + 53, 4 );
    return clamp( 0.82 + mid * 0.16 - crack * 0.22, 0.35, 1.0 );
  }
  if ( li == 1 ) {
    let dust = aeMtFbm( uv * 70.0, 70.0, s + 13, 3 );
    return clamp( 0.88 + dust * 0.14, 0.5, 1.0 );
  }
  if ( li == 2 || li == 3 ) {
    // Live grass has a waxy cuticle and is measurably less rough than dead
    // straw; that difference is most of what sells "lush" versus "burnt".
    let dry = f32( li == 3 );
    let clump = aeMtVoronoi( uv * 17.0, 17.0, s + 3 );
    let tuft = clamp( 1.0 - clump.x * 1.55, 0.0, 1.0 );
    return clamp( mix( 0.62, 0.86, dry ) + tuft * 0.10 - 0.08, 0.4, 1.0 );
  }
  if ( li == 4 ) {
    let moss = smoothstep( 0.15, 0.62, aeMtFbm( uv * 9.0, 9.0, s + 37, 3 ) + 0.5 );
    return clamp( 0.80 - moss * 0.14, 0.4, 1.0 );
  }
  if ( li == 5 ) {
    let grain = aeMtFbm( uv * 300.0, 300.0, s + 41, 2 );
    return clamp( 0.80 + grain * 0.16, 0.5, 1.0 );
  }
  if ( li == 6 ) {
    // Wet clay is the one genuinely smooth surface in the set, and where it has
    // dried it jumps back up. A single roughness for mud loses the whole effect.
    let dryness = smoothstep( 0.05, 0.55, aeMtFbm( uv * 6.0, 6.0, s + 47, 3 ) + 0.5 );
    let lumps = aeMtFbm( uv * 22.0, 22.0, s + 19, 4 );
    return clamp( mix( 0.24, 0.84, dryness ) + lumps * 0.10, 0.15, 1.0 );
  }
  // Snow: fresh powder is rough, wind-crust is glossy. The sparkle comes from
  // the high-frequency term, and it is what makes a snowfield look cold.
  let crust = aeMtFbm( uv * 120.0, 120.0, s + 29, 3 );
  let drifts = aeMtFbm( uv * 4.0, 4.0, s + 13, 3 );
  return clamp( 0.52 + drifts * 0.22 - crust * 0.26, 0.10, 0.95 );
}
`,
  [fnMtFbm, fnMtVoronoi],
);
