/**
 * The biome PBR set, synthesised on the GPU at startup into two
 * `texture_2d_array`s.
 *
 * Spec 2.3 asks for a texture array so the material can index a biome without
 * branching, KTX2-compressed, mipped, anisotropic. This delivers the array, the
 * mips and the anisotropy; what it does *not* deliver is authored art, and that
 * is a deliberate choice rather than an omission. There are no image assets in
 * this repo and the spec's 25 MB asset budget is spent at zero — the textures
 * are generated by `shaders/materialTextures.wgsl.ts` from the world seed. The
 * honest cost is stated there: procedural granite has structure and scale but
 * not the specificity of photographed granite.
 *
 * Two passes, for the same reason `HeightmapGenerator` uses two: the second one
 * has to read what the first wrote. Pass 1 evaluates albedo, height and
 * roughness per texel. Pass 2 derives the normal and the cavity AO *from the
 * stored height*, so they describe the surface actually sampled — and because
 * it reads neighbours with a wrap, the normal map tiles as seamlessly as the
 * height does. Deriving normals analytically inside pass 1 would need four
 * extra evaluations of a fairly expensive function and would still get the
 * wrap-around texels wrong.
 *
 * Mips are generated by three: a storage texture with `generateMipmaps` set is
 * allocated with a full chain, and the backend fills it the first time the
 * texture is bound for sampling after having been bound for storage. Mips are
 * not optional here — at 800 m the 1× detail is minified by three orders of
 * magnitude, and without a chain that is pure aliasing.
 */

import * as THREE from 'three/webgpu';
import {
  Fn,
  If,
  computeKernel,
  bitAnd,
  clamp,
  float,
  globalId,
  int,
  inverseSqrt,
  storageTexture,
  textureStore,
  uint,
  uniform,
  uvec2,
  vec2,
  vec4,
} from 'three/tsl';

import type { ResourceManager } from '@/engine/ResourceManager';
import { BIOME_COUNT } from './shaders/splat';
import { fnMatAlbedoHeight, fnMatRoughness } from './shaders/materialTextures.wgsl';

/**
 * Texels per edge of one biome's texture.
 *
 * 512 with a full mip chain is 8 × 512² × 4 B × 2 arrays × 4/3 = 22.4 MB, which
 * is the whole of this phase's memory cost. 1024 would be 89 MB for detail that
 * the 8× multi-scale sample already provides more cheaply: the second sample is
 * an eighth of the period, so the effective near-field resolution is 4096
 * without paying for a 4096² texture. Spec 2.3's rule — cut resolution before
 * cutting biome count — points the same way.
 */
export const MATERIAL_TEX_SIZE = 512;

/**
 * World size of one repeat of the 1× scale, metres.
 *
 * 2 m puts roughly one grass clump per 12 cm and one granite joint block per
 * 40 cm, which is what those features measure in life. It is also the number
 * the stochastic tiling has to defeat: at 2 m a naive repeat is a visible grid
 * from any altitude above about 50 m.
 */
export const MATERIAL_TEX_METRES = 2.0;

const WORKGROUP = 8;
const GROUPS = Math.ceil(MATERIAL_TEX_SIZE / WORKGROUP);

/**
 * How hard the derived normal leans.
 *
 * The height channel is 0..1 over `MATERIAL_TEX_METRES / MATERIAL_TEX_SIZE`
 * ≈ 4 mm per texel, so the geometrically exact slope would be near-vertical
 * everywhere and the surface would read as crumpled foil. Physical exactness is
 * the wrong target for a detail normal — this is tuned by eye against the
 * mountain shot, which is the only test that means anything here.
 */
const NORMAL_STRENGTH = 2.6;

/** Radius in texels of the cavity-AO ring. */
const AO_RADIUS = 5;

type ComputeKernelNode = ReturnType<typeof computeKernel>;

const _dispatch: number[] = [GROUPS, GROUPS, 1];

export class MaterialTextures {
  /** rgba8: rgb linear albedo, a ambient occlusion. */
  readonly albedoAO: THREE.StorageArrayTexture;
  /** rgba8: rg normal.xy (0.5-centred), b roughness, a height. */
  readonly normalRH: THREE.StorageArrayTexture;

  private uSeed = uniform(1337);
  private uLayer = uniform(0);

  private synthNode: ComputeKernelNode;
  private deriveNode: ComputeKernelNode;

  private generated = false;

  constructor(
    private renderer: THREE.WebGPURenderer,
    resources: ResourceManager,
    seed: number,
  ) {
    this.uSeed.value = seed;

    this.albedoAO = this.makeArray('terrain/matAlbedoAO');
    this.normalRH = this.makeArray('terrain/matNormalRH');

    // A mip chain adds 1/3 to the base level; count it, because the F3 memory
    // readout is only as honest as the registrations behind it.
    const bytes = Math.round(MATERIAL_TEX_SIZE * MATERIAL_TEX_SIZE * BIOME_COUNT * 4 * (4 / 3));
    resources.track(this.albedoAO, 'terrain/matAlbedoAO', bytes);
    resources.track(this.normalRH, 'terrain/matNormalRH', bytes);

    const seedNode = this.uSeed;
    const layerNode = this.uLayer;
    const inv = 1 / MATERIAL_TEX_SIZE;

    // --- pass 1: albedo, height, roughness --------------------------------
    const synth = Fn(() => {
      const gx = globalId.x;
      const gy = globalId.y;

      If(gx.lessThan(uint(MATERIAL_TEX_SIZE)).and(gy.lessThan(uint(MATERIAL_TEX_SIZE))), () => {
        const layer = int(layerNode);
        // Texel centres, so that the wrap at u=1 lands exactly one texel past
        // the wrap at u=0 rather than on top of it.
        const uv = vec2(float(gx).add(0.5), float(gy).add(0.5)).mul(inv);

        const ah = fnMatAlbedoHeight({ uv, layer: float(layerNode), seed: int(seedNode) });
        const rough = fnMatRoughness({ uv, layer: float(layerNode), seed: int(seedNode) });

        // AO starts at 1 and is replaced by pass 2. Writing it rather than
        // leaving the channel undefined means a failed second pass shows as
        // "no AO" rather than as garbage.
        textureStore(
          storageTexture(this.albedoAO).depth(layer),
          uvec2(gx, gy),
          vec4(ah.x, ah.y, ah.z, 1),
        );
        // Normal starts flat (0.5, 0.5) for the same reason.
        textureStore(
          storageTexture(this.normalRH).depth(layer),
          uvec2(gx, gy),
          vec4(0.5, 0.5, rough, ah.w),
        );
      });
    });

    this.synthNode = computeKernel(synth(), [WORKGROUP, WORKGROUP, 1]);
    this.synthNode.setName('matTexSynth');

    // --- pass 2: normal from height, cavity AO ----------------------------
    // One node per texture, read-write, used for *both* the loads and the
    // stores. Creating a separate write-only node for the store would give the
    // same texture two bindings with conflicting access modes, and the backend
    // resolves that by keeping one — which is how this pass first failed, with
    // Tint rejecting `textureLoad` on a `write`-access storage texture.
    const albedoRW = storageTexture(this.albedoAO).toReadWrite();
    const normalRW = storageTexture(this.normalRH).toReadWrite();

    const derive = Fn(() => {
      const gx = globalId.x;
      const gy = globalId.y;

      If(gx.lessThan(uint(MATERIAL_TEX_SIZE)).and(gy.lessThan(uint(MATERIAL_TEX_SIZE))), () => {
        const layer = int(layerNode);

        // Wrapped fetch. This is the whole reason the normal derivation is a
        // separate pass: the texel at u=0 needs the height at u=1, which only
        // exists once pass 1 has written it.
        // `bitAnd` rather than a modulo because the size is a power of two and
        // WGSL's `%` on a negative i32 keeps the dividend's sign — which would
        // index outside the texture on the left and bottom edges.
        const mask = int(MATERIAL_TEX_SIZE - 1);
        const heightAt = (dx: number, dy: number) => {
          const sx = bitAnd(int(gx).add(int(dx)), mask);
          const sy = bitAnd(int(gy).add(int(dy)), mask);
          return normalRW.depth(layer).load(uvec2(uint(sx), uint(sy))).w;
        };

        const h = heightAt(0, 0);
        const hL = heightAt(-1, 0);
        const hR = heightAt(1, 0);
        const hD = heightAt(0, -1);
        const hU = heightAt(0, 1);

        // Sobel would be smoother, but a 4-tap central difference keeps the
        // sharp edges of the Worley cracks sharp, and those edges are most of
        // what makes rock look like rock under a grazing sun.
        const dhdx = hR.sub(hL).mul(NORMAL_STRENGTH);
        const dhdy = hU.sub(hD).mul(NORMAL_STRENGTH);
        const len = inverseSqrt(dhdx.mul(dhdx).add(dhdy.mul(dhdy)).add(1));
        const nx = dhdx.mul(-1).mul(len);
        const ny = dhdy.mul(-1).mul(len);

        const nrh = normalRW.depth(layer).load(uvec2(gx, gy));
        textureStore(
          normalRW.depth(layer),
          uvec2(gx, gy),
          vec4(nx.mul(0.5).add(0.5), ny.mul(0.5).add(0.5), nrh.z, nrh.w),
        );

        // Cavity AO: how far below its neighbourhood this texel sits. A ring of
        // eight taps at a fixed radius rather than a box blur, because what we
        // want is "is this in a crack", and a crack is defined by the ground a
        // few millimetres to either side of it, not by a smooth average.
        const r = AO_RADIUS;
        const d = Math.round(r * 0.7071);
        const ring = heightAt(-r, 0)
          .add(heightAt(r, 0))
          .add(heightAt(0, -r))
          .add(heightAt(0, r))
          .add(heightAt(-d, -d))
          .add(heightAt(d, -d))
          .add(heightAt(-d, d))
          .add(heightAt(d, d))
          .mul(0.125);
        // 1 in the open, darkening into hollows. The asymmetry is intentional:
        // a bump is not brighter than flat ground, but a pit is darker.
        const ao = clamp(float(1).add(h.sub(ring).mul(1.9)), float(0.25), float(1));

        const alb = albedoRW.depth(layer).load(uvec2(gx, gy));
        textureStore(albedoRW.depth(layer), uvec2(gx, gy), vec4(alb.x, alb.y, alb.z, ao));
      });
    });

    this.deriveNode = computeKernel(derive(), [WORKGROUP, WORKGROUP, 1]);
    this.deriveNode.setName('matTexDerive');
  }

  private makeArray(label: string): THREE.StorageArrayTexture {
    const tex = new THREE.StorageArrayTexture(
      MATERIAL_TEX_SIZE,
      MATERIAL_TEX_SIZE,
      BIOME_COUNT,
    );
    tex.format = THREE.RGBAFormat;
    tex.type = THREE.UnsignedByteType;
    tex.name = label;
    // Linear colour throughout. The albedo is authored in linear directly, so
    // an sRGB view would double-decode it — and rgba8unorm-srgb is not a legal
    // storage format anyway, so asking for it would fail the texture creation.
    tex.colorSpace = THREE.NoColorSpace;
    tex.wrapS = THREE.RepeatWrapping;
    tex.wrapT = THREE.RepeatWrapping;
    tex.magFilter = THREE.LinearFilter;
    tex.minFilter = THREE.LinearMipmapLinearFilter;
    tex.generateMipmaps = true;
    // `mipmapsAutoUpdate` is declared on `StorageTexture` but *not* on
    // `StorageArrayTexture`, which extends `Texture` directly. three's binding
    // code gates auto-generation on `isStorageTexture && mipmapsAutoUpdate ===
    // true`, so without this the chain is allocated and never filled — and
    // sampling an unfilled mip returns black. That is exactly how this first
    // rendered: a correct texture at level 0 and a black world at every
    // distance where the sampler asked for level 1 or beyond.
    (tex as unknown as { mipmapsAutoUpdate: boolean }).mipmapsAutoUpdate = true;
    // Spec 2.3 asks for 8×–16×. 8 is the point where the cost stops being free
    // on tile-based hardware and the terrain is sampled at grazing angles over
    // most of the frame.
    tex.anisotropy = 8;
    return tex;
  }

  /**
   * Run both passes, one submit per biome layer.
   *
   * Per layer rather than one 512×512×8 dispatch because a single submit of
   * 2.1 M invocations of this much noise is long enough to be worth not handing
   * to a driver watchdog in one piece; splitting it also means the cost shows up
   * as eight small stalls during init instead of one large one.
   */
  generate(): void {
    if (this.generated) return;
    this.generated = true;

    for (let layer = 0; layer < BIOME_COUNT; layer++) {
      this.uLayer.value = layer;
      this.renderer.compute(this.synthNode, _dispatch);
      this.renderer.compute(this.deriveNode, _dispatch);
    }
  }

  dispose(): void {
    this.synthNode.dispose();
    this.deriveNode.dispose();
  }
}
